### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by gfrare** [JsonHunt/bookmark-panel#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.190.0
**System**: Mac OS X 10.9.5
**Thrown From**: [bookmark-panel](https://github.com/JsonHunt/bookmark-panel) package, v1.0.0
### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Users/gfrare/.atom/packages/bookmark-panel/lib/bookmark-panel.coffee:63

TypeError: Cannot read property 'length' of undefined
  at /Users/gfrare/.atom/packages/bookmark-panel/lib/bookmark-panel.coffee:63:52
  at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:302:5)

```
### Commands

```
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "disabledPackages": [
      "git-merge-conflicts",
      "status-stats",
      "notebook"
    ],
    "themes": [
      "atom-dark-ui",
      "solarized-dark-syntax"
    ],
    "audioBeep": false
  }
}
```
### Installed Packages

``` coffee
# User
Atom-Syntax-highlighting-for-Sass, v0.5.0
atom-handlebars, v0.4.0
atom-jshint, v1.5.0
autoclose-html, v0.15.0
autocomplete-plus, v2.9.0
bookmark-panel, v1.0.0
coffee-lint, v0.7.3
command-logger, v0.22.0
compare-files, v0.4.1
css-color-highlighting, v0.2.4
highlight-line, v0.10.1
language-arduino, v0.2.1
language-haml, v0.17.0
language-rspec, v0.3.0
project-manager, v1.15.5
selection-count, v1.6.3
space-tab, v0.1.0
tabs-to-spaces, v0.9.2
terminal-status, v1.6.0
trailing-spaces, v0.2.4

# Dev
No dev packages
```

**Comment by niklasHagner** [comment]
Same issue here. Using Atom 1.0.19 on Windows.

**Comment by ghost** [comment]
Same here, Atom 1.50.0 on Ubuntu 20.
`TypeError: Cannot read property 'length' of undefined
    at ReadFileContext.callback (.../.atom/packages/bookmark-panel/lib/bookmark-panel.coffee:63:53)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:247:13)`
