### ISSUE TITLE
Failed to activate the bookmark-panel package

### ISSUE THREAD

**Issue by assafg** [JsonHunt/bookmark-panel#2]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.204.0
**System**: Mac OS X 10.9.5
**Thrown From**: [bookmark-panel](https://github.com/JsonHunt/bookmark-panel) package, v1.0.0
### Stack Trace

Failed to activate the bookmark-panel package

```
At path is not defined

ReferenceError: path is not defined
  at Object.module.exports.BookmarkPanel.activate (/Users/gannona/.atom/packages/bookmark-panel/lib/bookmark-panel.coffee:18:75)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:238:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:219:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:163:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:211:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:435:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:345:29
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:41:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:227:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "atom-terminal-panel"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
bookmark-panel, v1.0.0
color-picker, v2.0.2
linter, v0.12.6
linter-jshint, v0.1.5
linter-rubocop, v0.2.7
minimap, v4.9.0
minimap-bookmarks, v0.1.0
tree-view-open-files, v0.2.3

# Dev
No dev packages
```

**Comment by Gkupce** [comment]
1. Install package

**Atom Version**: 1.3.2
**System**: Microsoft Windows 7 Ultimate 
**Thrown From**: [bookmark-panel](https://github.com/JsonHunt/bookmark-panel) package, v1.0.0

### Stack Trace

Failed to activate the bookmark-panel package

```
At path is not defined

ReferenceError: path is not defined
    at Object.module.exports.BookmarkPanel.activate (file:///C:/Users/Stavo/.atom/packages/bookmark-panel/lib/bookmark-panel.coffee:18:75)
    at Package.module.exports.Package.activateNow (C:\Users\Stavo\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package.js:170:19)
    at C:\Users\Stavo\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package.js:150:32
    at Package.module.exports.Package.measure (C:\Users\Stavo\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package.js:92:15)
    at C:\Users\Stavo\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package.js:143:26
    at Package.module.exports.Package.activate (C:\Users\Stavo\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Stavo\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package-manager.js:517:21)
    at C:\Users\Stavo\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:444:29
    at exit (C:\Users\Stavo\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\Stavo\AppData\Local\atom\app-1.3.2\resources\app.asar\src\buffered-process.js:213:47)
    at C:\Users\Stavo\AppData\Local\atom\app-1.3.2\resources\app.asar\src\buffered-process.js:220:18
    at Socket.<anonymous> (C:\Users\Stavo\AppData\Local\atom\app-1.3.2\resources\app.asar\src\buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
     -6:12.6.0 settings-view:open (atom-text-editor.editor.is-focused)
  2x -6:01.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
bookmark-panel, v1.0.0
language-shadercode, v2.0.0
line-diff-details, v1.1.3
minimap, v4.19.0
minimap-git-diff, v4.1.8
seti-icons, v0.4.5

# Dev
No dev packages
```

**Comment by CasusArts** [comment]
Atom Version: 1.5.0
System: Windows 10
Thrown From: bookmark-panel package, v1.0.0

[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.5.0
**System**: AEON
**Thrown From**: [bookmark-panel](https://github.com/JsonHunt/bookmark-panel) package, v1.0.0

### Stack Trace

Failed to activate the bookmark-panel package

```
At path is not defined

ReferenceError: path is not defined
    at Object.module.exports.BookmarkPanel.activate (file:///C:/Users/Casus/.atom/packages/bookmark-panel/lib/bookmark-panel.coffee:18:75)
    at Package.module.exports.Package.activateNow (C:\Users\Casus\AppData\Local\atom\app-1.5.0\resources\app.asar\src\package.js:183:20)
    at C:\Users\Casus\AppData\Local\atom\app-1.5.0\resources\app.asar\src\package.js:156:32
    at Package.module.exports.Package.measure (C:\Users\Casus\AppData\Local\atom\app-1.5.0\resources\app.asar\src\package.js:92:15)
    at C:\Users\Casus\AppData\Local\atom\app-1.5.0\resources\app.asar\src\package.js:149:26
    at Package.module.exports.Package.activate (C:\Users\Casus\AppData\Local\atom\app-1.5.0\resources\app.asar\src\package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Casus\AppData\Local\atom\app-1.5.0\resources\app.asar\src\package-manager.js:526:21)
    at C:\Users\Casus\AppData\Local\atom\app-1.5.0\resources\app.asar\src\package-manager.js:507:29
    at Config.module.exports.Config.transactAsync (C:\Users\Casus\AppData\Local\atom\app-1.5.0\resources\app.asar\src\config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\Casus\AppData\Local\atom\app-1.5.0\resources\app.asar\src\package-manager.js:502:19)
    at PackageManager.module.exports.PackageManager.activate (C:\Users\Casus\AppData\Local\atom\app-1.5.0\resources\app.asar\src\package-manager.js:485:46)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (C:\Users\Casus\AppData\Local\atom\app-1.5.0\resources\app.asar\src\atom-environment.js:688:21)
    at module.exports (C:\Users\Casus\AppData\Local\atom\app-1.5.0\resources\app.asar\src\initialize-application-window.js:28:10)
    at setupWindow (file:///C:/Users/Casus/AppData/Local/atom/app-1.5.0/resources/app.asar/static/index.js:86:5)
    at window.onload (file:///C:/Users/Casus/AppData/Local/atom/app-1.5.0/resources/app.asar/static/index.js:41:9)
```

### Commands

```
```

### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
bookmark-panel, v1.0.0
color-picker, v2.1.1
emmet, v2.4.1
emmet-snippets-compatibility, v1.0.4
file-bookmark, v0.3.1
keyboard-localization, v1.4.14
language-blade, v0.20.0
language-ejs, v0.2.0
language-nunjucks, v2.0.0
linter, v1.11.3
linter-twig, v0.1.0
minimap, v4.19.0
minimap-bookmarks, v0.2.0
minimap-codeglance, v0.4.5
minimap-pigments, v0.1.7
node-debugger, v1.3.2
nodejs-snippets, v2.0.0
php-twig, v4.0.0
pigments, v0.23.1
travis-ci-status, v1.0.0

# Dev
No dev packages
```

**Comment by Zireael07** [comment]
I'm having the same problem.

**Comment by zmiimz** [comment]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.3
**System**: "openSUSE 13.1
**Thrown From**: [bookmark-panel](https://github.com/JsonHunt/bookmark-panel) package, v1.0.0

### Stack Trace

Failed to activate the bookmark-panel package

```
At path is not defined

ReferenceError: path is not defined
    at Object.module.exports.BookmarkPanel.activate (/home/term/.atom/packages/bookmark-panel/lib/bookmark-panel.coffee:18:75)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:183:20)
    at /usr/share/atom/resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:538:21)
    at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:452:29
    at exit (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:215:47)
    at /usr/share/atom/resources/app.asar/src/buffered-process.js:229:18
    at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:100:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
     -0:12.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

``` json
{
  "core": {
    "disabledPackages": [
      "symbols-list",
      "atom-beautify",
      "autocomplete-bash-builtins",
      "autocomplete-html-entities",
      "autocomplete-java",
      "autocomplete-xml",
      "activate-power-mode"
    ],
    "themes": [
      "atom-light-ui",
      "atom-material-syntax"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
atom-material-syntax, v0.4.6
autocomplete-clang, v0.9.3
autocomplete-en-en, v0.2.0
autocomplete-json, v1.9.1
autocomplete-python, v1.7.2
bookmark-panel, v1.0.0
bottom-dock, v0.4.4
gcc-make-run, v0.2.6
language-cpp14, v0.6.1
language-opencl, v0.1.1
language-openmp, v0.2.0
linter, v1.11.4
linter-cppcheck, v0.2.0
linter-gfortran, v0.2.1
linter-matlab, v1.1.0
minimap, v4.23.5
minimap-cursorline, v0.1.0
minimap-find-and-replace, v4.5.1
minimap-hide, v0.3.0
minimap-linter, v1.1.1
minimap-pigments, v0.2.0
minimap-split-diff, v0.3.0
pigments, v0.26.2
process-palette, v0.8.1
symbols-plus, v0.1.1
symbols-tree-view, v0.12.0
terminal-plus, v0.14.5
todo-manager, v0.2.8

# Dev
No dev packages
```
