### ISSUE TITLE
Uncaught TypeError: Cannot read property 'remove' of undefined

### ISSUE THREAD

**Issue by adryweber** [JsonHunt/bookmark-panel#4]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: [bookmark-panel](https://github.com/JsonHunt/bookmark-panel) package, v1.0.0
### Stack Trace

Uncaught TypeError: Cannot read property 'remove' of undefined

```
At /Users/andreytkachenko/.atom/packages/bookmark-panel/lib/bookmark-panel.coffee:119

TypeError: Cannot read property 'remove' of undefined
  at Object.module.exports.BookmarkPanel.cleanPanel (/Users/andreytkachenko/.atom/packages/bookmark-panel/lib/bookmark-panel.coffee:119:14)
  at Object.module.exports.BookmarkPanel.refreshPanel (/Users/andreytkachenko/.atom/packages/bookmark-panel/lib/bookmark-panel.coffee:45:4)
  at Object.module.exports.BookmarkPanel.toggle (/Users/andreytkachenko/.atom/packages/bookmark-panel/lib/bookmark-panel.coffee:133:4)
  at atom-workspace.subscriptions.add.atom.commands.add.bookmark-panel:toggle (/Users/andreytkachenko/.atom/packages/bookmark-panel/lib/bookmark-panel.coffee:16:87)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:145:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:169:7)

```
### Commands

```
     -0:00.6.0 bookmark-panel:toggle (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "symbols-tree-view",
      "symbols-view",
      "file-bookmark"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
bookmark-panel, v1.0.0
spec-tree-view, v0.1.0

# Dev
No dev packages
```

**Comment by rafster** [comment]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Microsoft Windows 7 Home Premium 
**Thrown From**: [bookmark-panel](https://github.com/JsonHunt/bookmark-panel) package, v1.0.0

### Stack Trace

Uncaught TypeError: Cannot read property 'remove' of undefined

```
At /C:/Users/Ivonka/.atom/packages/bookmark-panel/lib/bookmark-panel.coffee:166

TypeError: Cannot read property 'remove' of undefined
    at Object.module.exports.BookmarkPanel.cleanPanel (file:///C:/Users/Ivonka/.atom/packages/bookmark-panel/lib/bookmark-panel.coffee:119:14)
    at Object.module.exports.BookmarkPanel.refreshPanel (file:///C:/Users/Ivonka/.atom/packages/bookmark-panel/lib/bookmark-panel.coffee:45:4)
    at Object.module.exports.BookmarkPanel.toggle (file:///C:/Users/Ivonka/.atom/packages/bookmark-panel/lib/bookmark-panel.coffee:133:4)
    at atom-workspace.subscriptions.add.atom.commands.add.bookmark-panel:toggle (file:///C:/Users/Ivonka/.atom/packages/bookmark-panel/lib/bookmark-panel.coffee:16:87)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Ivonka\AppData\Local\atom\app-1.3.2\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\Ivonka\AppData\Local\atom\app-1.3.2\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Ivonka\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Ivonka\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (C:\Users\Ivonka\AppData\Local\atom\app-1.3.2\resources\app.asar\src\window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (C:\Users\Ivonka\AppData\Local\atom\app-1.3.2\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
     -6:21 core:paste (atom-text-editor.editor.mini.is-focused)
     -6:20.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:33.6.0 core:copy (div.package-detail.panels-item)
     -0:33.5.0 tab-switcher:next (div.package-detail.panels-item)
     -0:25.3.0 bookmark-panel:toggle (atom-text-editor.editor.is-focused)
```

### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "browser-plus",
      "preview-plus"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
bookmark-panel, v1.0.0
highlight-line, v0.11.0
highlight-selected, v0.11.1
last-cursor-position, v0.9.0
minimap, v4.19.0
minimap-bookmarks, v0.2.0
minimap-codeglance, v0.4.5
minimap-find-and-replace, v4.4.0
minimap-highlight-selected, v4.3.1
minimap-selection, v4.3.1
open-in-browsers, v0.0.7
tab-switcher, v1.3.3

# Dev
No dev packages
```

**Comment by CasusArts** [comment]
**Atom Version**: 1.5.0
**System**: Windows 10
**Thrown From**: [bookmark-panel](https://github.com/JsonHunt/bookmark-panel) package, v1.0.0

### Stack Trace

Uncaught TypeError: Cannot read property 'remove' of undefined

```
At /C:/Users/Casus/.atom/packages/bookmark-panel/lib/bookmark-panel.coffee:166

TypeError: Cannot read property 'remove' of undefined
    at Object.module.exports.BookmarkPanel.cleanPanel (file:///C:/Users/Casus/.atom/packages/bookmark-panel/lib/bookmark-panel.coffee:119:14)
    at Object.module.exports.BookmarkPanel.refreshPanel (file:///C:/Users/Casus/.atom/packages/bookmark-panel/lib/bookmark-panel.coffee:45:4)
    at Object.module.exports.BookmarkPanel.toggle (file:///C:/Users/Casus/.atom/packages/bookmark-panel/lib/bookmark-panel.coffee:133:4)
    at atom-workspace.subscriptions.add.atom.commands.add.bookmark-panel:toggle (file:///C:/Users/Casus/.atom/packages/bookmark-panel/lib/bookmark-panel.coffee:16:87)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Casus\AppData\Local\atom\app-1.5.0\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\Casus\AppData\Local\atom\app-1.5.0\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\Casus\AppData\Local\atom\app-1.5.0\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (C:\Users\Casus\AppData\Local\atom\app-1.5.0\resources\app.asar\src\atom-environment.js:1013:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```

### Commands

```
     -0:56.4.0 core:close (div.pane-item.native-key-bindings.about)
     -0:03.9.0 bookmark-panel:toggle (a.btn-copy-report.icon.icon-clippy)
```

### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
bookmark-panel, v1.0.0
color-picker, v2.1.1
emmet, v2.4.1
emmet-snippets-compatibility, v1.0.4
file-bookmark, v0.3.1
keyboard-localization, v1.4.14
language-blade, v0.20.0
language-ejs, v0.2.0
language-nunjucks, v2.0.0
linter, v1.11.3
linter-twig, v0.1.0
minimap, v4.19.0
minimap-bookmarks, v0.2.0
minimap-codeglance, v0.4.5
minimap-pigments, v0.1.7
node-debugger, v1.3.2
nodejs-snippets, v2.0.0
php-twig, v4.0.0
pigments, v0.23.1
travis-ci-status, v1.0.0

# Dev
No dev packages
```
